### ISSUE TITLE
Voters didnt received email

### ISSUE THREAD

**Issue by jakubcere** [benadida/helios-server#273] opened 2020-12-03 17:37 UTC
I have a very urgent problem with voting. In 16 hours starts an important election for school president with 2320 voters. I have used your website to create an election and have uploaded voters.
But I have sended email with their ID and password and they didn't received it. Noone.

https://vote.heliosvoting.org/helios/e/volby_srvs_FEI_STU  

Thanks for your help.

**Comment by cristianmonterom** [comment] 2020-12-16 14:17
I was testing this web app and I figured out that Helios does not send mails by itself. When you do "bulk upload voters" , after you must enter to "voters & ballots" then to "email voters". There you have to chose which message you want to send and finally select recipient(s).

I hope it helps

**Comment by changuinho2000** [comment] 2021-01-29 16:14
I can confirm that yahoo users dont receive email for vote, probably a Yahoo issue.

**Comment by benadida** [comment] 2021-01-29 16:18
This issue should now be fixed, I've tested it with yahoo email addresses. @changuinho2000 how recently did you try?

**Comment by changuinho2000** [comment] 2021-01-29 16:38
Hello, lol I was wondering how to contact you....I ran some elections from october 2020 to january 2021, using browser and not a Linux server...confirmed Yahoo cant receive, probably they delete it, and the e-mail doenst even appears in SPAM folder.....
Actually, I am trying to setup an election and when I click on Bulk upload voters, it shows the four first voters, and when I click LETS GO, it shows this error "There was an error while handling your request.", but now I realized that its not an instant process.... I have to wait ? I got this error before with some accentuation like í, á, ã characters in voters list, as the spaces can result in an error....I would like to delete the elections, all I can do is to archive them....Thank you....I will try it later, because I got many NOT PROCESSED YET errors, maybe its that what is causing the error.....thank you

**Comment by benadida** [comment] 2021-02-06 17:43
This should be fixed now. Please try again and report back if you still see delivery issues.

**Closed by benadida** 2021-02-06 17:43 UTC
