### ISSUE TITLE
Editing an election question resets the ballot type

### ISSUE THREAD

**Issue by sigmavirus24** [benadida/helios-server#99] opened 2015-06-10 22:22 UTC
At present moment an administrator sees:

> Select between [dropdown - default: 0] and [dropdown - default: 1] answers.

If I select "approval", save the question, then go back and edit it, it restores the default to 1 instead of honoring the previous selection.

I would expect that it would preserve the previous value that I had specified instead of resetting it.

**Comment by shirlei** [comment] 2015-09-14 11:58
Hello! I use the system and I couldn't reproduce this issue... Could you elaborate it a bit more?

**Comment by benadida** [comment] 2016-05-09 00:53
agree, I can't reproduce, closing

**Closed by benadida** 2016-05-09 00:53 UTC
