### ISSUE TITLE
pyparsing-1.5.7 failes

### ISSUE THREAD

**Issue by simon1tan** [benadida/helios-server#144] opened 2017-02-21 17:59 UTC
While running pip install -r requirements.txt, I am getting:

> Collecting pyparsing==1.5.7 (from -r requirements.txt (line 9))
>   Using cached pyparsing-1.5.7.zip
>     Complete output from command python setup.py egg_info:
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/home/www/helios-server/venv/local/lib/python2.7/site-packages/setuptools/__init__.py", line 12, in <module>
>         import setuptools.version
>       File "/home/www/helios-server/venv/local/lib/python2.7/site-packages/setuptools/version.py", line 1, in <module>
>         import pkg_resources
>       File "/home/www/helios-server/venv/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 72, in <module>
>         import packaging.requirements
>       File "/home/www/helios-server/venv/local/lib/python2.7/site-packages/packaging/requirements.py", line 59, in <module>
>         MARKER_EXPR = originalTextFor(MARKER_EXPR())("marker")
>     TypeError: __call__() takes exactly 2 arguments (1 given)
>     
>     ----------------------------------------
> Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-kSBuDW/pyparsing/
> 

Not sure if installing the latest version (2.1.10 ) would be compatible or not.

**Comment by sapienman** [comment] 2017-04-07 02:13
+1

**Comment by dimitriskr** [comment] 2017-04-18 17:14
Any solution on this?

**Comment by dmgawel** [comment] 2017-04-18 20:30
It looks like this package is no longer used (at least I cannot find any direct import and use of it). You can try removing `pyparsing` from `requirements.txt`.

**Comment by dimitriskr** [comment] 2017-04-20 11:37
I can confirm that by removing the `pyparsing` from `requirements.txt` did not create any issue while installing the server and I have now access to it

**Comment by benadida** [comment] 2017-05-11 13:23
are you still seeing this? Which version of Python are you using? I recommend sticking with `2.7` for now.

**Comment by benadida** [comment] 2017-05-24 05:05
not seeing issues with python 2.7... closing. If this is still an issue, please reopen!

**Closed by benadida** 2017-05-24 05:05 UTC
